### ISSUE TITLE
Set up Axios & Redux & RTK Query

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/apprenticeship-movies-app#33]

**Comment by olets** [comment]
We'll use Axios for fetching data from tmdb

@solomonhawk what were we going to use Redux/TK for? Is that related to when users are signed in?

**Comment by olets** [comment]
Remembered search pagination. Do we want pagination based on state or routes? (My inclination is routes but am good with either.)

**Comment by solomonhawk** [comment]
RTK Query definitely (for caching TMDB data), redux only if necessary.

Pagination - URL
