### ISSUE TITLE
Storybook on staging

### ISSUE THREAD

**Issue by olets** [vigetlabs/apprenticeship-movies-app#61]
Would be helpful for code review QA if Storybook were visible on Netlify. I think what that will take is

1. Add storybook npm scripts
2. Make a new Netlify or Vercel project (whichever you prefer) using this repo
3. Set up the build steps to include running the storybook build

I haven't put Storybook on either of these services. There may be gotchas.

**Comment by mpurcella** [comment]
1: I believe the storybook script is already added. Will double check if another is needed. In progress...
2: https://gleaming-pie-741a18.netlify.app/
3: In progress...
